// Code generated by 'yaegi extract github.com/suifengpiao14/yaegijson'. DO NOT EDIT.

package yaegijson

import (
	"reflect"
)

func init() {
	Symbols["github.com/suifengpiao14/yaegijson/yaegijson"] = map[string]reflect.Value{
		// function, constant and variable definitions
		//"Error_not_found_func": reflect.ValueOf(&yaegijson.Error_not_found_func).Elem(),
		"GetValueFromJson":     reflect.ValueOf(GetValueFromJson),
		

		// type definitions
		//"DynamicExtension": reflect.ValueOf((*yaegijson.DynamicExtension)(nil)),
	}
}
